fail_fast: false
exclude: "^coverage/"

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-yaml
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
    - repo: local
      hooks:
          - id: prettier
            name: prettier
            description: Format TypeScript / JS / JSON / MD …
            entry: npx prettier --write --ignore-unknown .
            language: node
            types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]
          - id: audit
            name: npm audit
            description: Scan for known vulnerable dependencies
            entry: bash -c 'npm audit --audit-level=moderate --registry https://registry.npmjs.org'
            language: node
            pass_filenames: false
          - id: typos
            name: typos
            description: Check for spelling mistakes
            entry: typos
            language: node
            pass_filenames: false
          - id: tsc
            name: tsc
            description: Type-check the whole project
            entry: bash -c 'npx tsc --noEmit'
            language: node
            pass_filenames: false
          - id: eslint
            name: eslint
            description: Lint TypeScript / JavaScript sources
            entry: npx eslint --fix --max-warnings 0
            language: node
            types_or: [javascript, jsx, ts, tsx]
          - id: jest
            name: jest
            description: Run tests with Jest
            entry: bash -c 'npm test'
            language: node
            files: \.(ts|tsx|js|jsx)$
            pass_filenames: true
