name: build

on:
    push:
        branches: [master]
        tags: ["v*"]
    pull_request:
        branches: [master]

permissions:
    contents: write

jobs:
    build-ts:
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-latest]
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
                  submodules: recursive

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Lint & Format (Prettier + ESLint)
              run: npm run lint

            - name: Type check (tsc)
              run: npx tsc --noEmit

            - name: Run Jest tests
              run: npm run test:cov

            - name: Upload coverage
              uses: codecov/codecov-action@v5
              if: matrix.platform == 'ubuntu-latest'
              with:
                  files: ./coverage/lcov.info
                  token: ${{ secrets.CODECOV_TOKEN }}

            - name: Generate changelog
              if: startsWith(github.ref, 'refs/tags/')
              uses: orhun/git-cliff-action@v4
              id: git-cliff
              with:
                  config: cliff.toml
                  args: -vv --latest --strip header
              env:
                  OUTPUT: CHANGELOG.md
            - name: Release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  body: ${{ steps.git-cliff.outputs.content }}
                  files: |
                      coverage/lcov.info
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    changelog:
        needs: build-ts
        if: github.event_name == 'push' && github.ref_name == 'master'
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0
                  ref: ${{ github.head_ref || github.ref_name }}

            - name: Generate CHANGELOG
              uses: orhun/git-cliff-action@v4
              with:
                  args: --output CHANGELOG.md

            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update CHANGELOG.md"
                  file_pattern: CHANGELOG.md
